apiVersion: v1
kind: configmap
metadata:
  name: my-app-pod
  namespace: myimage1
spec:
  containers:
    - name: my-app-container
      image: my-app-image:latest
      envFrom:
        - configMapRef:
            name: my-configmap 

  
